version: '3'

services:
  app_im:
    build: ./
    command: ./short-link
    ports:
      - "8080:8080"

  app_db:
    build: ./
    command: ./wait-for-postgres.sh db ./short-link -storage=true
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/Link?sslmode=disable"
      DB_PASSWORD: "postgres"

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
